### ISSUE TITLE
prompt should only have one 

### ISSUE THREAD

**Issue by gaoqi7** [evantravers/hammerspoon#10]
Under default config, when use "Hyper + m" trigger split modal, it will show one prompt. 

If I accidentally trigger twice, there will be two prompts(alert) showing on the screen. only the second one  can be cancelled by "ctrl + [".

**Comment by evantravers** [comment]
Thanks for the poke to finally get after this one! I'm slowly rewriting my hammerspoon setup to be a little more independent of my weird config table.

Just so that I can help you with your needs, is the window movement part the only part of my config that you are using, or are you using my configuration wholesale?

**Comment by evantravers** [comment]
@megalithic… I'm debating making movewindows.lua into a spoon… it seems like a very personal set of scripts, not really a provider of functionality… and it depends (at the moment) on:

- Hyper.spoon
- Split.spoon

**Comment by evantravers** [comment]
@gaoqi7 I pushed a change that makes the hotkey toggle the movewindows prompt.

**Comment by evantravers** [comment]
@gaoqi7 Thanks for prompting me to clean up my act… I appreciate it!

If movewindows.lua was the only part you used, it's been extracted into it's own spoon now: https://github.com/evantravers/MoveWindows.spoon/tree/847ba991b6c6c3e5d7894fc0431b6de720422487

**Comment by gaoqi7** [comment]
> Thanks for the poke to finally get after this one! I'm slowly rewriting my hammerspoon setup to be a little more independent of my weird config table.
> 
> Just so that I can help you with your needs, is the window movement part the only part of my config that you are using, or are you using my configuration wholesale?

I use all your configuration right now and plan use this as my base setting for future customize. so far so great, thanks for the sharing.
