### ISSUE TITLE
secrets.lau missing required items

### ISSUE THREAD

**Issue by SFDCkbernstein** [evantravers/hammerspoon#15]
Can you provide a better sample of what secrets.lau needs to include in order for Headspace to run.  Init.lau gacks on "Config.projects = hs.settings.get("secrets").toggl.projects"

Checked your website and don't see it mentioned there either. Thanks!

**Comment by evantravers** [comment]
Hey @SFDCkbernstein!

Great question! There is an example of the JSON file in this post: https://evantravers.com/articles/2020/06/13/hammerspoon-toggl-api-calls-and-secret-tokens/

```json
{
  "standupURL": "http://evantravers.com",
  "standupCall": "https://meet.google.com/respect-op-sec",
  "toggl": {
    "key": "<my key>",
    "projects": {
      "communications": "123456789",
      "meetings": "123456789",
      "planning": "123456789",
      "reading": "123456789",
      "design": "123456789",
      "research": "123456789",
      "play": "123456789",
      "leadership": "123456789"
    }
  }
}
```

Pretty much anything you put into a json key value pair will be loaded into a table in hs.settings

**Comment by muescha** [comment]
I don't find a place where you use the secrets

**Comment by muescha** [comment]
ok - found some places:

https://github.com/evantravers/hammerspoon-config/blob/8cdbd816c5fd687ffcbb97ed5426a1fd856d88a5/init.lua#L198

https://github.com/evantravers/hammerspoon-config/blob/8cdbd816c5fd687ffcbb97ed5426a1fd856d88a5/init.lua#L229-L231

https://github.com/evantravers/hammerspoon-config/blob/5cfa47c664942ee1b4a3fa49598e64121505970b/spaces/collaboration.lua#L10

**Comment by evantravers** [comment]
That's right @muescha, nice gif spelunking.

I mostly used them for API keys for Toggl.com, but I recently refactored my Headspace spoon to be idempotent of Toggl so that more could use them. Maybe I should spin off secrets.lua as a Spoon?

**Comment by muescha** [comment]
I see your security.lua is used in many repos :)

A spoon would be a nice addition.


PS:
For myself I added a `security.get()` so I don't need to mess up with `hs.settings`

```lua
module.get = function()
    if hs.settings.get("secrets") then
        return hs.settings.get("secrets")
    else
        print("Error: You need to to define secrets!")
    end

end
```

**Comment by muescha** [comment]
also i would like a better fallback when a key (for example `sessings.get().toggle.key`) is not defined in the secrets.

**Comment by evantravers** [comment]
> I see your security.lua is used in many repos :)

I'll be dogged. Guess I will spin it off indeed, thanks @muescha.

**Comment by evantravers** [comment]
Thanks to @muescha's suggestion, I have spun off secrets.lua into [Secrets.spoon](https://github.com/evantravers/Secrets.spoon). I'm not currently using it in my setup, but I've updated it a little bit:

- error handling for missing keys via `assert`
- new `get()` function that supports both `dot.style.lookup` and `{"table", "style", "lookup"}`. I think the table could be handy for building a "query" for more complicated structures.

I'm going to (somewhat rudely) ping @reinier, @danielo515, @thenoseman, @catesandrew, and @aldur in case they find this useful. 🙏

**Comment by danielo515** [comment]
> Thanks to @muescha's suggestion, I have spun off secrets.lua into [Secrets.spoon](https://github.com/evantravers/Secrets.spoon). I'm not currently using it in my setup, but I've updated it a little bit:
> 
> * error handling for missing keys via `assert`
> * new `get()` function that supports both `dot.style.lookup` and `{"table", "style", "lookup"}`. I think the table could be handy for building a "query" for more complicated structures.
> 
> I'm going to (somewhat rudely) ping @reinier, @danielo515, @thenoseman, @catesandrew, and @aldur in case they find this useful. 🙏

Thank you for putting the time to split this into a spoon. So far, I think I will stick with my copied pasted version (with the due credit). The code is not that complex, and I like to be in full control of it.
But it is good to know this is around!
